[global]
error_log = /var/www/html/storage/logs/fpm-error.log
daemonize = no

[www]
access.log = /var/www/html/storage/logs/fpm-access.log
catch_workers_output = yes
decorate_workers_output = no
php_admin_value[error_log] = /var/www/html/storage/logs/php-error.log
php_admin_flag[log_errors] = on